### PR TITLE
feat: Simplify import_sorter command

### PR DESCRIPTION
**Pull request by mrgnhnt96**
The current command to run import sorter is

```console
# as a dev dependency
dart run import_sorter:main

# globally
dart pub global run import_sorter:main
```

With this change, the `:main` can be omitted,  making the command more intuitive

```console
# as dev dependency
dart run import_sorter

# globally
dart pub global run import_sorter
```

The `:main` command will not be removed to avoid breaking existing projects using import_sorter, but could be considered in the future. I've added a deprecated warning whenever `import_sorter:main` is used.

image

### CODE REVIEW

**Comment by vkammerer** [comment]
Thanks @mrgnhnt96 for the PR, I think it's a good idea.

But if the idea is to deprecate the `:main` syntax in a future version, could you please redo your PR this way:
- rename `bin/main.dart` to `bin/import_sorter.dart` in a first commit.
- then do a second commit that adds a new `bin/main.dart` that points to `bin/import_sorter.dart`, and also includes the deprecation warning.

Then please force push your branch.

That way, when we remove support for the `:main` syntax, we'll just have to delete the `bin/main.dart` file. It will also keep the deprecation warning isolated, not mixed with the rest of the logic.

**Comment by vkammerer** [comment]
Also, please add a third commit that removes references to `:main` from the documentation. See all current occurrences at https://github.com/search?q=repo%3Afluttercommunity%2Fimport_sorter%20%3Amain&type=code

**Comment by pythonhubdev** [comment]
@vkammerer once this is merged can we make a new release to pub.dev?

**Comment by vkammerer** [comment]
@mrgnhnt96 Thanks for updating your PR.

Could you look into why the `import_sorter` Github action is failing?
https://github.com/fluttercommunity/import_sorter/actions/runs/7592158197/job/20790428773

**Comment by mrgnhnt96** [comment]
> @mrgnhnt96 Thanks for updating your PR.
> 
> Could you look into why the `import_sorter` Github action is failing? https://github.com/fluttercommunity/import_sorter/actions/runs/7592158197/job/20790428773

I hadn't run import sorter lol, I just fixed it. It should pass now

**Comment by vkammerer** [comment]
Thanks @mrgnhnt96 , that made the tests pass.

I'll update the CHANGELOG and prepare a release to pub.dev

**Comment by vkammerer** [comment]
@slightfoot We would like to make a new release to pub.dev. Would you be able to help us with it?

**Comment by vkammerer** [comment]
This was finally published on pub.dev, under the version `5.0.0-releasecandidate.1`

**Pull request merged**
