### PR TITLE
Package update with lint rules

### PR DESCRIPTION
**Pull request by pythonhubdev**
- [x] Updated packages to latest version
- [x] Added lint rules
- [x] Updated the example app with latest flutter version

### CODE REVIEW

**Comment by lig** [comment]
Personally, I would like to see those things being a separate PRs.

- Updating dependencies is a routine operation that could be implemented separately.
- Fixing documentation grammar could go in it's own separate PR to prevent it be blocked by less trivial changes.

Also, IMO, linting rules shouldn't change current code style drastically but rather embrace it. I mean, if project mostly uses single quotes that what should we put in as a linting rule.

**Comment by pythonhubdev** [comment]
Sure will do as required @lig

**Comment by vkammerer** [comment]
@pythonhubdev I think you split your original PR into too many PRs now: They can't pass the tests individually.
It would be ideal if you only took out the "grammar" fixes in a PR, and left all the rest in a single PR.

So could you open one PR with the contents of https://github.com/fluttercommunity/import_sorter/pull/71, https://github.com/fluttercommunity/import_sorter/pull/72 and https://github.com/fluttercommunity/import_sorter/pull/74 ?

I've checked out your branch https://github.com/pythonhubdev/import_sorter/tree/github_actions and I can see that we'll have to add a few changes to make sure the tests pass and to merge. But I'd rather comment on the PR you'll create than to spread comments across multiple ones

**Comment by pythonhubdev** [comment]
Sure will do it

**Comment by pythonhubdev** [comment]
#75 please check this PR

**Pull request closed without merging**
